- hosts: localhost
  gather_facts: no
  vars:
    shibboleth_host: shibboleth.jpayne.do.rancher.space
  tasks:
  - name: Enable ssl apache module
    apache2_module:
      name: ssl
      state: present
  - name: Enable proxy apache module
    apache2_module:
      name: proxy
      state: present
  - name: Copy apache site
    template:
      src: apache/idp.conf.j2
      dest: /etc/apache2/sites-available/idp.conf
  - name: Enable site
    command: "a2ensite idp"