- hosts: localhost
  gather_facts: no
  vars:
    # Shibboleth
    shibboleth_host: shibboleth.jpayne.do.rancher.space
    shibboleth_backchannelsigning_cert: ""
    shibboleth_frontchannelsigning_cert: ""


  # TODO: prompt for host
  # TODO: generate ldap info
  tasks:
    - name: Copy idp tomcat configuration
      copy:
        src: tomcat/idp.xml
        dest: /etc/tomcat8/Catalina/localhost/idp.xml
    - name: Copy tomcat server configuration
      copy:
        src: tomcat/server.xml
        dest: /etc/tomcat8/server.xml
