- hosts: localhost
  gather_facts: no
  vars:
    shibboleth_host: shibboleth.jpayne.do.rancher.space
  tasks:
    - name: Copy idp tomcat configuration
      template:
        src: tomcat/idp.xml.j2
        dest: /etc/tomcat8/Catalina/localhost/idp.xml
    - name: Copy tomcat server configuration
      template:
        src: tomcat/server.xml.j2
        dest: /etc/tomcat8/server.xml